---

- name: Install apt-transport-https
  become: true
  apt:
    pkg: "apt-transport-https"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family != 'Darwin'

- name: Add Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    state: present
  when: ansible_os_family != 'Darwin'

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://cli.github.com/packages stable main
    state: present
  when: ansible_os_family != 'Darwin'

- name: Install GitHub CLI
  become: true
  apt:
    pkg: "gh"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family != 'Darwin'

- name: Install GitHub CLI (Mac)
  become: false
  homebrew:
    name: gh
    state: present
  when: ansible_os_family == 'Darwin'
