---

- name: Install Python packages
  become: true
  apt: 
    pkg: ["python3", "python3-dev", "python3-pip"]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family != 'Darwin'
