---

- name: Install apt-transport-https
  become: true
  apt:
    pkg: "apt-transport-https"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family != 'Darwin'

- name: Add Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  when: ansible_os_family != 'Darwin'

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
  when: ansible_os_family != 'Darwin'

- name: Install google-chrome-stable
  become: true
  apt:
    pkg: "google-chrome-stable"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family != 'Darwin'

- name: Install Google Chrome (Mac)
  become: false
  homebrew_cask:
    name: google-chrome
    state: present
  when: ansible_os_family == 'Darwin'